spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pet_store
    username: "pet-store"
    password: "pet-store"
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
